<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>gradle</string>
	</array>
	<key>name</key>
	<string>Gradle</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\s*(task)\s+(\w+)\s*\(.*type: Copy.*\)\s*{</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.task.source.gradle</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>tasks.Copy.body.source.gradle</string>
			<key>end</key>
			<string>}</string>
			<key>name</key>
			<string>Copy.task.source.gradle</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>caseSensitive</string>
					<key>name</key>
					<string>support.function.task.tasks.Copy.gradle</string>
				</dict>
				<dict>
					<key>match</key>
					<string>destinationDir</string>
					<key>name</key>
					<string>support.function.task.tasks.Copy.gradle</string>
				</dict>
				<dict>
					<key>match</key>
					<string>dirMode</string>
					<key>name</key>
					<string>support.function.task.tasks.Copy.gradle</string>
				</dict>
				<dict>
					<key>match</key>
					<string>duplicatesStrategy</string>
					<key>name</key>
					<string>support.function.task.tasks.Copy.gradle</string>
				</dict>
				<dict>
					<key>match</key>
					<string>excludes</string>
					<key>name</key>
					<string>support.function.task.tasks.Copy.gradle</string>
				</dict>
				<dict>
					<key>match</key>
					<string>fileMode</string>
					<key>name</key>
					<string>support.function.task.tasks.Copy.gradle</string>
				</dict>
				<dict>
					<key>match</key>
					<string>includeEmptyDirs</string>
					<key>name</key>
					<string>support.function.task.tasks.Copy.gradle</string>
				</dict>
				<dict>
					<key>match</key>
					<string>includes</string>
					<key>name</key>
					<string>support.function.task.tasks.Copy.gradle</string>
				</dict>
				<dict>
					<key>match</key>
					<string>source</string>
					<key>name</key>
					<string>support.function.task.tasks.Copy.gradle</string>
				</dict>
				<dict>
					<key>match</key>
					<string>eachFile</string>
					<key>name</key>
					<string>support.function.task.tasks.Copy.gradle</string>
				</dict>
				<dict>
					<key>match</key>
					<string>exclude</string>
					<key>name</key>
					<string>support.function.task.tasks.Copy.gradle</string>
				</dict>
				<dict>
					<key>match</key>
					<string>expand</string>
					<key>name</key>
					<string>support.function.task.tasks.Copy.gradle</string>
				</dict>
				<dict>
					<key>match</key>
					<string>filesMatching</string>
					<key>name</key>
					<string>support.function.task.tasks.Copy.gradle</string>
				</dict>
				<dict>
					<key>match</key>
					<string>filesNotMatching</string>
					<key>name</key>
					<string>support.function.task.tasks.Copy.gradle</string>
				</dict>
				<dict>
					<key>match</key>
					<string>filter</string>
					<key>name</key>
					<string>support.function.task.tasks.Copy.gradle</string>
				</dict>
				<dict>
					<key>match</key>
					<string>from</string>
					<key>name</key>
					<string>support.function.task.tasks.Copy.gradle</string>
				</dict>
				<dict>
					<key>match</key>
					<string>include</string>
					<key>name</key>
					<string>support.function.task.tasks.Copy.gradle</string>
				</dict>
				<dict>
					<key>match</key>
					<string>into</string>
					<key>name</key>
					<string>support.function.task.tasks.Copy.gradle</string>
				</dict>
				<dict>
					<key>match</key>
					<string>rename</string>
					<key>name</key>
					<string>support.function.task.tasks.Copy.gradle</string>
				</dict>
				<dict>
					<key>match</key>
					<string>with</string>
					<key>name</key>
					<string>support.function.task.tasks.Copy.gradle</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.groovy</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\s*(task)\s+(\w+)\s*\(.*type: Exec.*\)\s*{</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.task.source.gradle</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>tasks.Exec.body.source.gradle</string>
			<key>end</key>
			<string>}</string>
			<key>name</key>
			<string>Exec.task.source.gradle</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>args</string>
					<key>name</key>
					<string>keyword.task.tasks.Exec.gradle</string>
				</dict>
				<dict>
					<key>match</key>
					<string>commandLine</string>
					<key>name</key>
					<string>keyword.task.tasks.Exec.gradle</string>
				</dict>
				<dict>
					<key>match</key>
					<string>environment</string>
					<key>name</key>
					<string>keyword.task.tasks.Exec.gradle</string>
				</dict>
				<dict>
					<key>match</key>
					<string>errorOutput</string>
					<key>name</key>
					<string>keyword.task.tasks.Exec.gradle</string>
				</dict>
				<dict>
					<key>match</key>
					<string>execResult</string>
					<key>name</key>
					<string>keyword.task.tasks.Exec.gradle</string>
				</dict>
				<dict>
					<key>match</key>
					<string>executable</string>
					<key>name</key>
					<string>keyword.task.tasks.Exec.gradle</string>
				</dict>
				<dict>
					<key>match</key>
					<string>ignoreExitValue</string>
					<key>name</key>
					<string>keyword.task.tasks.Exec.gradle</string>
				</dict>
				<dict>
					<key>match</key>
					<string>standardInput</string>
					<key>name</key>
					<string>keyword.task.tasks.Exec.gradle</string>
				</dict>
				<dict>
					<key>match</key>
					<string>standardOutput</string>
					<key>name</key>
					<string>keyword.task.tasks.Exec.gradle</string>
				</dict>
				<dict>
					<key>match</key>
					<string>workingDir</string>
					<key>name</key>
					<string>keyword.task.tasks.Exec.gradle</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.groovy</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.task.source.gradle</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Task definitions</string>
			<key>match</key>
			<string>\s*(task)\s+(\w+)</string>
			<key>name</key>
			<string>task.source.gradle</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.gradle</string>
	<key>uuid</key>
	<string>b5741d4f-485d-4bca-9a5b-6a1ec2a5a272</string>
</dict>
</plist>
